// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination interface_mock.go -package service . Service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	repository "github.com/the-code-genin/golang_integration_testing/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockService) CreateNote(ctx context.Context, dto repository.CreateNoteDTO) (*repository.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, dto)
	ret0, _ := ret[0].(*repository.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockServiceMockRecorder) CreateNote(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockService)(nil).CreateNote), ctx, dto)
}

// DeleteNote mocks base method.
func (m *MockService) DeleteNote(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockServiceMockRecorder) DeleteNote(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockService)(nil).DeleteNote), ctx, id)
}

// FetchNoteByID mocks base method.
func (m *MockService) FetchNoteByID(ctx context.Context, id uuid.UUID) (*repository.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNoteByID", ctx, id)
	ret0, _ := ret[0].(*repository.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNoteByID indicates an expected call of FetchNoteByID.
func (mr *MockServiceMockRecorder) FetchNoteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNoteByID", reflect.TypeOf((*MockService)(nil).FetchNoteByID), ctx, id)
}

// FetchNotes mocks base method.
func (m *MockService) FetchNotes(ctx context.Context) ([]repository.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNotes", ctx)
	ret0, _ := ret[0].([]repository.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNotes indicates an expected call of FetchNotes.
func (mr *MockServiceMockRecorder) FetchNotes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNotes", reflect.TypeOf((*MockService)(nil).FetchNotes), ctx)
}

// UpdateNote mocks base method.
func (m *MockService) UpdateNote(ctx context.Context, id uuid.UUID, dto repository.UpdateNoteDTO) (*repository.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, id, dto)
	ret0, _ := ret[0].(*repository.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockServiceMockRecorder) UpdateNote(ctx, id, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockService)(nil).UpdateNote), ctx, id, dto)
}
