// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination interface_mock.go -package repository . Repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockRepository) CreateNote(ctx context.Context, dto CreateNoteDTO) (*Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, dto)
	ret0, _ := ret[0].(*Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockRepositoryMockRecorder) CreateNote(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockRepository)(nil).CreateNote), ctx, dto)
}

// DeleteNote mocks base method.
func (m *MockRepository) DeleteNote(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockRepositoryMockRecorder) DeleteNote(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockRepository)(nil).DeleteNote), ctx, id)
}

// FetchNoteByID mocks base method.
func (m *MockRepository) FetchNoteByID(ctx context.Context, id uuid.UUID) (*Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNoteByID", ctx, id)
	ret0, _ := ret[0].(*Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNoteByID indicates an expected call of FetchNoteByID.
func (mr *MockRepositoryMockRecorder) FetchNoteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNoteByID", reflect.TypeOf((*MockRepository)(nil).FetchNoteByID), ctx, id)
}

// FetchNotes mocks base method.
func (m *MockRepository) FetchNotes(ctx context.Context) ([]Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNotes", ctx)
	ret0, _ := ret[0].([]Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNotes indicates an expected call of FetchNotes.
func (mr *MockRepositoryMockRecorder) FetchNotes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNotes", reflect.TypeOf((*MockRepository)(nil).FetchNotes), ctx)
}

// UpdateNote mocks base method.
func (m *MockRepository) UpdateNote(ctx context.Context, id uuid.UUID, dto UpdateNoteDTO) (*Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, id, dto)
	ret0, _ := ret[0].(*Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockRepositoryMockRecorder) UpdateNote(ctx, id, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockRepository)(nil).UpdateNote), ctx, id, dto)
}
